### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Xelcronia** [Ad5001/UHC#9]
I don't know if I'm doing it right. When i do /uhc start, it says I'm not in the uhc world or it's already started. 
## My config: 

LobbyWorld: skyspawn
# Set your worlds here !

worlds: 
world: cave 
radius: 1000
maxplayers: 32
default_scenarios: []
# Will be added if you add scenarios

scenarios: []
...

Also how do i let players join the game? With /scenario?
Will i be able to set up a sign?

**Comment by Ad5001** [comment]
I see. You need to add a space before each world like so:

``` yaml
worlds:
  world: cave
    radius: 1000
    maxplayers: 32
    default_scenarios: []
```

To let people join, just add a signso they can join your world and they will be in ^^
Get me in touch if you get any other errors.

**Comment by Xelcronia** [comment]
Okay. I will try. Thank you :)

**Comment by Xelcronia** [comment]
Still the same error. I tped to the world using manyworlds and tried the command.

My config right now: 

```
---
LobbyWorld: skyspawn
# Set your worlds here !
worlds:
  world: cave
    radius: 1000
    maxplayers: 32
    default_scenarios: []

# Will be added if you add scenarios
scenarios: []
...
```

P.S. : it's  a PC ported map.

**Comment by Ad5001** [comment]
Do you load the world before loading the UHC plugin?

**Comment by Xelcronia** [comment]
Should the world be loaded before UHC? It does only when i tp to it.

**Comment by Ad5001** [comment]
No. Strange... Did you do the exact name of the world (including caps?)

**Comment by Ad5001** [comment]
Oh oops! My bad the config should be like this:

``` yaml
worlds:
  cave:
    world: cave
      radius: 1000
      maxplayers: 32
      default_scenarios: []
```

NOW this should work.

**Comment by Xelcronia** [comment]
Lemme try

**Comment by Xelcronia** [comment]
Nope still the same ;-; 

```
---
LobbyWorld: skyspawn
# Set your worlds here !
worlds:
  cave:
    world: cave
      radius: 1000
      maxplayers: 32
      default_scenarios: []

# Will be added if you add scenarios
scenarios: []
...
```

**Comment by Ad5001** [comment]
Added, one more time, too much space ;-; I hate so much yaml

``` yaml
worlds:
  cave:
    name: cave
    radius: 1000
    maxplayers: 32
    default_scenarios: []
```

So now if it doesn't work, I will make all my plugins with JSON.
